import { createContext, useContext, useState, useEffect } from "react";
import type { ReactNode } from "react";

export type Language = "uk" | "en";

export const translations = {
  uk: {
    brand: "Якість документації Prozorro",
    notice: "Автоматичні сигнали потребують перевірки людиною",
    userRequests: "Запити користувачів",
    allReviews: "Всі перевірки",
    autoSignals: "автоматичні сигнали",
    adminPanel: "адмін-панель",
    search: "Пошук",
    searchPlaceholder: "Назва товару, код ДК, ЄДРПОУ компанії, UA-номер або фраза...",
    category: "Категорія",
    allCategories: "Усі категорії",
    sector: "Сектор",
    allSectors: "Усі сектори",
    priority: "Пріоритет",
    allPriorities: "Усі пріоритети",
    maxScore: "Максимальний бал",
    sorting: "Сортування",
    activeFilters: "Активні фільтри",
    filtersCount: "фільтрів",
    reset: "Скинути",
    scoreLimit: "бал",
    sort_processed_desc: "Новіші спочатку",
    sort_score_asc: "Нижчий бал спочатку",
    sort_score_desc: "Вищий бал спочатку",
    sort_priority_desc: "Вищий пріоритет спочатку",
    sort_priority_asc: "Нижчий пріоритет спочатку",
    sort_value_desc: "Більша вартість спочатку",
    tenderCode: "Код тендера",
    buyer: "Замовник",
    score: "Бал",
    riskPriority: "Пріоритет",
    date: "Дата",
    loading: "Завантаження...",
    noTenders: "Тендери не знайдені.",
    errorLoading: "Помилка завантаження результатів.",
    page: "Сторінка",
    processing: "Опрацювання...",
    inProgress: "в процесі",
    batchTitle: "Обробка партії",
    batchSubtitle: "новити тендери",
    limit: "Кількість",
    llmExpl: "LLM пояснення",
    processBtn: "Обробити",
    uuidTitle: "Тендери за UUID",
    uuidSubtitle: "один або кілька",
    uuidInputLabel: "Prozorro UUID",
    addMoreUuid: "Додати ще один UUID",
    checkBtn: "Перевірити",
    draftTitle: "Аналіз чернетки",
    draftSubtitle: "перед публікацією",
    customTitleLabel: "Назва закупівлі *",
    customTitlePlaceholder: "Закупівля комп'ютерного обладнання",
    customDescLabel: "Опис та вимоги",
    customDescPlaceholder: "Введіть опис предмета закупівлі або детальні технічні вимоги...",
    customCpvLabel: "Код CPV",
    customCpvPlaceholder: "Наприклад: 30230000-0",
    customBudgetLabel: "Бюджет, грн",
    customSectorLabel: "Галузь",
    customFilesLabel: "Тендерна документація (файли)",
    checkDraftBtn: "Перевірити чернетку",
    backToList: "До списку",
    overallScoreLabel: "Загальний бал",
    priorityLevel: "пріоритет",
    subscoresLabel: "Підбали",
    potentialRisksTab: "Потенційні ризики закупівлі",
    requirementsTab: "Огляд вимог та дедлайнів",
    techDetailsTab: "Технічні деталі та статистика",
    detectedSignalsLabel: "Виявлені сигнали",
    ownerToggleLabel: "Я замовник (власник тендера)",
    explanationLabel: "Пояснення:",
    suggestedRewriteLabel: "Можливе переписування:",
    noRisksFound: "Потенційних ризиків за поточними правилами не знайдено. Це не замінює ручну перевірку документації.",
    parsedDocumentsLabel: "Опрацьовані документи",
    analysisLimitationsLabel: "Обмеження аналізу",
    technicalStatsLabel: "Технічна статистика опрацювання",
    llmModelLabel: "Модель аналізу:",
    tokensUsedLabel: "Використано токенів:",
    approxCostLabel: "Орієнтовна вартість API:",
    statusLabel: "Статус:",
    parsedCharsLabel: "Символів розпізнано:",
    noDocuments: "Документів не знайдено.",
    noLimitations: "Жодних обмежень аналізу не зафіксовано.",
    notCalculated: "не рахувалось",
    sev_high: "високий",
    sev_medium: "середній",
    sev_low: "низький",
    sev_none: "без сигналів",
    heuristicsTitle: "Автоматичні евристики аналізу",
    heuristicsDescription: "Повний перелік правил та шаблонів регулярних виразів, які використовуються нашою системою для автоматичного виявлення дискримінаційних умов та ризиків у документації.",
    activeSignalsCount: "активних сигналів",
    moderationTab: "Правила та модерація",
    miningTab: "Історія запусків майнінгу",
    userLlmTab: "Історія LLM-пояснень користувачів",
    adminTitle: "Панель керування якістю Prozorro",
    runMiningTitle: "Запуск автоматичного LLM-пошуку дискримінаційних умов",
    mineBtn: "Запустити пошук",
    runningStatus: "Аналіз запущено в бекграунді. Будь ласка, зачекайте...",
    rulesToReview: "Правила на модерації",
    activeRules: "Активні правила",
    rejectedRules: "Відхилені правила",
    emptyRules: "Правил у цій категорії немає.",
    approve: "Схвалити",
    reject: "Відхилити",
    evidenceRegex: "Регулярний вираз виявлення:",
    whyItMatters: "Чому це важливо:",
    subscoresAffected: "Підбали, на які впливає:",
    severityLevel: "Рекомендована критичність:",
    suggestedFix: "Рекомендація щодо виправлення:",
    miningHistoryTitle: "Історія запусків автоматичного пошуку",
    userLlmHistoryTitle: "Історія LLM-пояснень користувачів",
    requestedAt: "Час запиту",
    analyzedTenders: "Проаналізовано тендерів",
    cost: "Вартість",
    statusHeader: "Статус",
    errorHeader: "Помилка",
    tokensHeader: "Токени",
    actionHeader: "Дія",
    viewTender: "Переглянути",
    avgScoreMetric: "Сер. бал якості",
    avgScoreSub: "оцінка від 0 до 100",
    totalTendersMetric: "Всього перевірено",
    totalTendersSub: "база опрацьованих",
    highRiskMetric: "Високий пріоритет",
    highRiskSub: "потребують уваги",
    totalIssuesMetric: "Всього сигналів",
    totalIssuesSub: "знайдено правилами",
    llmCostMetric: "Вартість LLM",
    llmCostSub: "короткі Codex-запити",
    riskScale: "Шкала пріоритетів",
    activeSectors: "Активні галузі",
    recentTenders: "Останні перевірки",
    severity_висока: "висока",
    severity_середня: "середня",
    severity_низька: "низька",
    severity_немає: "немає",

    // HeuristicsView
    loadingRules: "Завантаження списку правил виявлення ризиків...",
    errorLoadingHeuristics: "Помилка завантаження евристик",
    totalHeuristics: "Усього евристик",
    highSeverity: "Висока критичність",
    mediumSeverity: "Середня критичність",
    lowSeverity: "Низька критичність",
    searchHeuristicsPlaceholder: "Шукати евристику за назвою, описом або категорією...",
    recommendedEdit: "Рекомендоване редагування:",
    noRulesFound: "Нічого не знайдено за вашим запитом.",
    allPill: "Усі",

    // AdminView
    adminLoginTitle: "Вхід до адмін-панелі",
    adminLoginSubtitle: "Будь ласка, авторизуйтесь для керування автоматичними сигналами.",
    usernameLabel: "Ім'я користувача",
    passwordLabel: "Пароль",
    loginBtn: "Увійти",
    loggingInBtn: "Вхід...",
    logoutBtn: "Вийти",
    adminSubtitle: "Керування автоматичними правилами аналізу та перегляд історії LLM-операцій.",
    autoLlmSearchTitle: "Автоматичний LLM-пошук нових евристик",
    autoLlmSearchDesc: "Запуск фонового аналізу останніх тендерів з Prozorro для виявлення нових дискримінаційних умов.",
    miningInProgress: "Аналіз тендерів у фоні...",
    tenders3: "3 тендери",
    tenders5: "5 тендерів",
    tenders10: "10 тендерів",
    tenders20: "20 тендерів",
    needModeration: "Потребують модерації",
    deactivateBtn: "Деактивувати",
    activateBtn: "Активувати",
    approveBtn: "Затвердити",
    rejectBtn: "Відхилити",
    showPattern: "Показати вираз",
    hidePattern: "Сховати вираз",
    emptyCategoryRules: "Немає правил у цій категорії.",
    loadingHistory: "Завантаження історії...",
    historyEmpty: "Історія запусків порожня",
    thStartTime: "Час запуску",
    thTendersCount: "Кількість тендерів",
    thResultsNewRules: "Результати / Нові правила",
    thStatus: "Статус",
    thRequestCost: "Вартість запиту (USD)",
    foundCount: "Знайдено: ",
    statusSuccess: "Успішно",
    statusMining: "Пошук...",
    statusFailed: "Помилка",
    userLlmHistoryDesc: "Перелік генерацій пояснень дискримінаційних умов та оцінки ризиків, що були активовані користувачами для конкретних тендерів.",
    noUserLlmRequests: "Немає запитів на пояснення від користувачів",
    thTenderCode: "Код тендера",
    thProcurementTitle: "Назва закупівлі",
    thRequestTime: "Час запиту",
    thTokensUsed: "Використано токенів",
    thCostUSD: "Вартість (USD)",
    invalidLoginError: "Неправильний логін або пароль",
    authError: "Помилка авторизації",

    // App.tsx additional keys
    tenderLoadingOrNotFound: "Тендер завантажується або не знайдено",
    pleaseWaitOrReturn: "Будь ласка, зачекайте або поверніться",
    toTheList: "до списку",
    qualityOverview: "Огляд якості тендерів",
    actionsAndRisks: "Дії та ризики",
    invalidUuidError: "Будь ласка, введіть коректні 32-значні Prozorro UUID без дефісів.\nНекоректні значення: ",
    errorFailedToRefresh: "Не вдалося оновити список результатів",
    errorFailedToProcessDraft: "Не вдалося обробити чернетку",
    errorStatusChange: "Не вдалося змінити статус",
    errorFailedToStartMining: "Не вдалося запустити автоматичний пошук",
  },


  en: {
    brand: "Prozorro Documentation Quality",
    notice: "Automated signals require human verification",
    userRequests: "User Requests",
    allReviews: "All Reviews",
    autoSignals: "automated signals",
    adminPanel: "admin panel",
    search: "Search",
    searchPlaceholder: "Product title, CPV code, company USREOU, UA-number, or phrase...",
    category: "Category",
    allCategories: "All categories",
    sector: "Sector",
    allSectors: "All sectors",
    priority: "Priority",
    allPriorities: "All priorities",
    maxScore: "Maximum score",
    sorting: "Sorting",
    activeFilters: "Active filters",
    filtersCount: "filters",
    reset: "Reset",
    scoreLimit: "score",
    sort_processed_desc: "Newest first",
    sort_score_asc: "Lowest score first",
    sort_score_desc: "Highest score first",
    sort_priority_desc: "Highest priority first",
    sort_priority_asc: "Lowest priority first",
    sort_value_desc: "Highest budget first",
    tenderCode: "Tender Code",
    buyer: "Buyer",
    score: "Score",
    riskPriority: "Priority",
    date: "Date",
    loading: "Loading...",
    noTenders: "No tenders found.",
    errorLoading: "Error loading results.",
    page: "Page",
    processing: "Processing...",
    inProgress: "in progress",
    batchTitle: "Batch Processing",
    batchSubtitle: "refresh tenders",
    limit: "Count",
    llmExpl: "LLM Explanation",
    processBtn: "Process",
    uuidTitle: "Tenders by UUID",
    uuidSubtitle: "one or more",
    uuidInputLabel: "Prozorro UUID",
    addMoreUuid: "Add another UUID",
    checkBtn: "Check",
    draftTitle: "Draft Analysis",
    draftSubtitle: "before publishing",
    customTitleLabel: "Procurement Title *",
    customTitlePlaceholder: "Purchase of computer equipment",
    customDescLabel: "Description & Requirements",
    customDescPlaceholder: "Enter description of the procurement item or detailed technical specifications...",
    customCpvLabel: "CPV Code",
    customCpvPlaceholder: "Example: 30230000-0",
    customBudgetLabel: "Budget, UAH",
    customSectorLabel: "Sector",
    customFilesLabel: "Tender Documentation (files)",
    checkDraftBtn: "Verify Draft",
    backToList: "Back to list",
    overallScoreLabel: "Overall Score",
    priorityLevel: "priority",
    subscoresLabel: "Subscores",
    potentialRisksTab: "Potential Procurement Risks",
    requirementsTab: "Requirements & Deadlines Overview",
    techDetailsTab: "Technical Details & Statistics",
    detectedSignalsLabel: "Detected Signals",
    ownerToggleLabel: "I am the buyer (tender owner)",
    explanationLabel: "Explanation:",
    suggestedRewriteLabel: "Suggested rewrite:",
    noRisksFound: "No potential risks found under current rules. This does not replace manual document review.",
    parsedDocumentsLabel: "Processed Documents",
    analysisLimitationsLabel: "Analysis Limitations",
    technicalStatsLabel: "Technical Processing Statistics",
    llmModelLabel: "Analysis model:",
    tokensUsedLabel: "Tokens used:",
    approxCostLabel: "Approximate API cost:",
    statusLabel: "Status:",
    parsedCharsLabel: "Characters parsed:",
    noDocuments: "No documents found.",
    noLimitations: "No analysis limitations recorded.",
    notCalculated: "not calculated",
    sev_high: "high",
    sev_medium: "medium",
    sev_low: "low",
    sev_none: "no signals",
    heuristicsTitle: "Automated analysis heuristics",
    heuristicsDescription: "A complete list of rules and regular expression patterns used by our system to automatically detect discriminatory conditions and risks in documentation.",
    activeSignalsCount: "active signals",
    moderationTab: "Rules & Moderation",
    miningTab: "Mining Run Logs",
    userLlmTab: "User LLM Explanation History",
    adminTitle: "Prozorro Quality Admin Panel",
    runMiningTitle: "Launch Automatic LLM Search for Discriminatory Conditions",
    mineBtn: "Launch Search",
    runningStatus: "Analysis started in background. Please wait...",
    rulesToReview: "Rules to Moderate",
    activeRules: "Active Rules",
    rejectedRules: "Rejected Rules",
    emptyRules: "No rules in this category.",
    approve: "Approve",
    reject: "Reject",
    evidenceRegex: "Detection Regex Pattern:",
    whyItMatters: "Why it matters:",
    subscoresAffected: "Affected subscores:",
    severityLevel: "Recommended severity:",
    suggestedFix: "Suggested fix guideline:",
    miningHistoryTitle: "Automated Search Run History",
    userLlmHistoryTitle: "User LLM Explanation History",
    requestedAt: "Requested At",
    analyzedTenders: "Tenders Analyzed",
    cost: "Cost",
    statusHeader: "Status",
    errorHeader: "Error",
    tokensHeader: "Tokens",
    actionHeader: "Action",
    viewTender: "View Details",
    avgScoreMetric: "Avg Quality Score",
    avgScoreSub: "score from 0 to 100",
    totalTendersMetric: "Total Reviews",
    totalTendersSub: "processed database",
    highRiskMetric: "High Priority",
    highRiskSub: "require attention",
    totalIssuesMetric: "Total Signals",
    totalIssuesSub: "found by rules",
    llmCostMetric: "LLM Cost",
    llmCostSub: "short Codex queries",
    riskScale: "Priority Scale",
    activeSectors: "Active Sectors",
    recentTenders: "Recent Checks",
    severity_висока: "high",
    severity_середня: "medium",
    severity_низька: "low",
    severity_немає: "none",

    // HeuristicsView
    loadingRules: "Loading risk detection rules...",
    errorLoadingHeuristics: "Error loading heuristics",
    totalHeuristics: "Total heuristics",
    highSeverity: "High severity",
    mediumSeverity: "Medium severity",
    lowSeverity: "Low severity",
    searchHeuristicsPlaceholder: "Search heuristics by title, description or category...",
    recommendedEdit: "Recommended editing:",
    noRulesFound: "Nothing found for your request.",
    allPill: "All",

    // AdminView
    adminLoginTitle: "Admin Panel Login",
    adminLoginSubtitle: "Please log in to manage automated signals.",
    usernameLabel: "Username",
    passwordLabel: "Password",
    loginBtn: "Log In",
    loggingInBtn: "Logging In...",
    logoutBtn: "Log Out",
    adminSubtitle: "Manage automated analysis rules and view LLM operations history.",
    autoLlmSearchTitle: "Automatic LLM Search for New Heuristics",
    autoLlmSearchDesc: "Launch background analysis of recent Prozorro tenders to detect new discriminatory conditions.",
    miningInProgress: "Analyzing tenders in background...",
    tenders3: "3 tenders",
    tenders5: "5 tenders",
    tenders10: "10 tenders",
    tenders20: "20 tenders",
    needModeration: "Need Moderation",
    deactivateBtn: "Deactivate",
    activateBtn: "Activate",
    approveBtn: "Approve",
    rejectBtn: "Reject",
    showPattern: "Show pattern",
    hidePattern: "Hide pattern",
    emptyCategoryRules: "No rules in this category.",
    loadingHistory: "Loading history...",
    historyEmpty: "Run history is empty",
    thStartTime: "Start Time",
    thTendersCount: "Tenders Count",
    thResultsNewRules: "Results / New Rules",
    thStatus: "Status",
    thRequestCost: "Request Cost (USD)",
    foundCount: "Found: ",
    statusSuccess: "Success",
    statusMining: "Searching...",
    statusFailed: "Failed",
    userLlmHistoryDesc: "List of generated explanations of discriminatory conditions and risk assessments triggered by users for specific tenders.",
    noUserLlmRequests: "No explanation requests from users",
    thTenderCode: "Tender Code",
    thProcurementTitle: "Procurement Title",
    thRequestTime: "Request Time",
    thTokensUsed: "Tokens Used",
    thCostUSD: "Cost (USD)",
    invalidLoginError: "Invalid username or password",
    authError: "Authorization error",

    // App.tsx additional keys
    tenderLoadingOrNotFound: "Tender is loading or not found",
    pleaseWaitOrReturn: "Please wait or return",
    toTheList: "to the list",
    qualityOverview: "Tender quality overview",
    actionsAndRisks: "Actions and risks",
    invalidUuidError: "Please enter valid 32-character Prozorro UUIDs without hyphens.\nInvalid values: ",
    errorFailedToRefresh: "Failed to refresh the list of results",
    errorFailedToProcessDraft: "Failed to process draft",
    errorStatusChange: "Failed to change status",
    errorFailedToStartMining: "Failed to launch automatic search",
  }
};


interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: keyof typeof translations.uk) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Language>(() => {
    return (localStorage.getItem("app_language") as Language) || "uk";
  });

  useEffect(() => {
    localStorage.setItem("app_language", lang);
    document.documentElement.lang = lang;
  }, [lang]);

  const t = (key: keyof typeof translations.uk): string => {
    return translations[lang][key] || translations.uk[key] || String(key);
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useTranslation() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useTranslation must be used within a LanguageProvider");
  }
  return context;
}
